server:
  port: 8000

spring:
  datasource:
    username: course-schedule
    password: course-schedule
    url: jdbc:mysql://101.35.55.200:3306/course-schedule?useSSL=false&serverTimezone=UTC

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      enabled: false
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liverpooooool.courseschedule.controller.rest
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#logging:
#  level:
#    web: trace
mybatis-plus:
  type-aliases-package: com.liverpooooool.courseschedule.persistence.entity
  mapper-locations:
    - classpath:com/liverpooooool/courseschedule/persistence/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
